services:
  - type: web
    name: pipedrive-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PIPEDRIVE_API_TOKEN
        sync: false   # legg inn verdien i Render-dashboardet
      - key: PIPEDRIVE_BASE
        value: https://api.pipedrive.com/v1
      - key: TZ
        value: Europe/Oslo

  - type: cron
    name: pipedrive-daily-sweep
    schedule: "0 6 * * *"    # 06:00 UTC = 08:00 Oslo (sommer)
    env: docker
    plan: free
    command: |
      bash -lc 'curl -X POST "$DAILY_SWEEP_URL" -H "Content-Type: application/json"'
    envVars:
      - key: DAILY_SWEEP_URL
        sync: false  # settes etter at web-URLen er klar
